"""
backtest_engine/events.py
Defines the core Event classes for the event-driven backtesting engine.
Includes Market, Signal, Order, and Fill events.
"""

from typing import Any, Dict
from enum import Enum

class EventType(Enum):
    MARKET = "MARKET"
    SIGNAL = "SIGNAL"
    ORDER = "ORDER"
    FILL = "FILL"


class Event:
    """Base class for all events."""
    pass


class MarketEvent(Event):
    """
    Triggered when a new market data bar (or tick) arrives.
    """
    def __init__(self):
        self.type = EventType.MARKET


class SignalEvent(Event):
    """
    Triggered by a Strategy when a trading signal is generated.
    """
    def __init__(self, symbol: str, timestamp: Any, signal_type: str, strength: float = 1.0, meta: Dict = None):
        self.type = EventType.SIGNAL
        self.symbol = symbol
        self.timestamp = timestamp
        self.signal_type = signal_type  # 'LONG', 'SHORT', 'EXIT'
        self.strength = strength
        self.meta = meta or {}


class OrderEvent(Event):
    """
    Sent to the ExecutionHandler to place an order.
    """
    def __init__(self, symbol: str, order_type: str, quantity: int, direction: str, price: float = None):
        self.type = EventType.ORDER
        self.symbol = symbol
        self.order_type = order_type  # 'MKT', 'LMT', 'STP'
        self.quantity = quantity
        self.direction = direction    # 'BUY', 'SELL'
        self.price = price

    def print_order(self):
        print(f"Order: {self.direction} {self.quantity} {self.symbol} {self.order_type} @ {self.price}")


class FillEvent(Event):
    """
    Generated by the ExecutionHandler when an Order is filled.
    """
    def __init__(
        self, timestamp: Any, symbol: str, exchange: str, 
        quantity: int, direction: str, fill_price: float, 
        commission: float = 0.0, slippage: float = 0.0
    ):
        self.type = EventType.FILL
        self.timestamp = timestamp
        self.symbol = symbol
        self.exchange = exchange
        self.quantity = quantity
        self.direction = direction
        self.fill_price = fill_price
        self.commission = commission
        self.slippage = slippage

    @property
    def cost(self) -> float:
        return (self.fill_price * self.quantity) + self.commission + self.slippage
